name = "Base"
author = "Kriticales"
version = "0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b84e1a03a78ccb6d56e8ce60bcf63fae93757672799b5f1d3307c3aad705a751"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
